### PR TITLE
[EPO-436] Implement and improve EPO python libraries

### PR DESCRIPTION
**Pull request by jmatt**
* Add `astropixie.data` module.
  * Add add `astropixie-hr` library.
  * Add `astropixie_hr.config` to support local and remote deployments
    and avoid a circular depedency when importing.
    *This should be moved to maybe a `astropixie_bokeh` when other
    libraries are added.*
  * Increment version of `astropixie` and `astropixie_hr` libraries
    to 0.1.0.

	modified:   .gitignore
	deleted:    astropixie-hr/astropixie-hr/__init__.py
	new file:   astropixie-hr/astropixie_hr/__init__.py
	new file:   astropixie-hr/astropixie_hr/config.py
	renamed:    astropixie-hr/astropixie-hr/science.py -> astropixie-hr/astropixie_hr/science.py
	renamed:    astropixie-hr/astropixie-hr/visual.py -> astropixie-hr/astropixie_hr/visual.py
	modified:   astropixie-hr/setup.py
	modified:   astropixie/astropixie/__init__.py
	renamed:    astropixie-hr/astropixie-hr/data.py -> astropixie/astropixie/data.py
	modified:   astropixie/astropixie/sample_catalog_provider.py
	modified:   astropixie/astropixie/types.py
	modified:   astropixie/setup.py

### CODE REVIEW

**Comment by cbanek** [comment]
Instead of calling it astropixie-hr, which implies that we'll have a new module for each investigation, I think it's probably a better idea to just call it astropixie-widgets or something, and stick all the widgets in the same module.

**Comment by cbanek** [comment]
Better yet, call it astrowidgets, so we don't have a dash or underscore in the name.  Or some other name that doesn't have a dash.  Just seems like trouble.

**Comment by jmatt** [comment]
I like having a lot of them and isolating changes. But I guess we could rename it to astropixie-widgets. The dash and underscore is common all over python. The hard part is done - getting it to work the first time.

**Comment by cbanek** [comment]
What does the isolation give us?  It seems to make things more complicated, and I'm not sure what we're gaining from it.  It all has to go in the container together anyway.

**Pull request merged**
